default_branch: main

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme@pcmultlectwithmasterormain

kramdown:
   parse_block_html: true

include:
   - _pages
exclude:
   - vendor
   - setup.sh
   - jekyll.sh
   - .sass-cache
   - Gemfile
   - LICENSE
   - .bundle

timezone: America/Los_Angeles

url: https://allolib-s22.github.io # the base hostname & protocol for your site
baseurl: /  # the subpath of your site, e.g. "/blog"
github_url: https://github.com/allolib-s22/allolib-s22.github.io



course: "Allolib s22"
qtr: "s22"
qxx: "s22"
quarter: "Spring 2021"

lecture_days_of_week: TR

assigned_text: " assigned"
due_text: " due "

start_week: 1
start_date: 2022-03-27
num_weeks: 10
extra_exam_week: true

cal_dates: >
  [                                                                            
    {"label":"S22 1st day of instruction", "date":"2022-03-27" },
    {"label":"Memorial Day", "date":"2022-05-30" },
    {"label":"S22 instruction ends", "date":"2022-06-03" },
    {"label":"S22 finals start", "date":"2022-06-04" },                     
    {"label":"S22 CS156 FINAL (4pm-7pm)", "date":"2022-06-07" },                      
    {"label":"S22 finals end", "date":"2022-06-10" },                          
    {"label":"S22 qtr ends", "date":"2022-06-10" }                              
  ]



gauchospace_course_page: https://gauchospace.ucsb.edu/courses/course/view.php?id=tbd
github_org_name: allolib-s22
github_org_url: https://github.com/allolib-s22

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  hwkWIP:
    output: true
    permalink: /hwkWIP/:path/
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/
  staff:
    output: true
    permalink: /staff/:path



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: hwkWIP
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
  -
    scope:
     path: ""
     type: staff
    values:
     layout: staff

  - scope:
     path: ""
     type: pages
    values:
     layout: default

head_scripts:
   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
   - /static/js/select_section.js
